### PR TITLE
3.0 Rewrite

### LINKED ISSUE #8: Fail to draw the page on the first load
Refreshing the page and it works again, but why?

### PR DESCRIPTION
**Pull request by eight04**
Fixes #8.

Todos:

* [x] Context menu.
* [x] Hotkey.

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+    browser.tabs.onRemoved.removeListener(onRemoved);
+    waitForUpdate.delete(tabId);
+  }
+  
+  function onUpdated(_tabId, changeInfo, tab) {
+    if (_tabId !== tabId || tab.url !== url) {
+      return;
+    }
+    browser.tabs.executeScript(tabId, {
+      file: "/js/browser-polyfill.min.js"
```
Comment (eight04) [inline src/background.js]: Import the file array from manifest.json.

File: src/content.js [hunk 2]
```diff
@@ -0,0 +1,104 @@
+/* eslint-env webextensions */
+import {createPmore} from "./pmore.js";
+import {createScrollPosSaver} from "./scroll-pos-saver.js";
+
+function getBinary(file, type = "blob"){
+	return new Promise((resolve, reject) => {
```
Comment (eight04) [inline src/content.js]: Fix the indent.

File: src/content.js [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+        binary = newBinary;
+        return compileANSI(binary)
+          .then(result => document.querySelector(".bbs").innerHTML = result.html);
+      })
+      .then(() => setTimeout(drawANSILoop, LOOP_TIMEOUT, binary));
+  }
+}
+
+if (
+  document.contentType == "text/plain" ||
```
Comment (eight04) [inline src/content.js]: contentType is already checked in the webRequest handler.

File: src/pmore.js [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+    } else {
+      return;
+    }
+    
+    e.preventDefault();
+  }
+}
+
+function createViewer(onend) {
+	var statusBar = document.querySelector(".statusbar"),
```
Comment (eight04) [inline src/pmore.js]: Fix the indent.
